# Generated by Django 4.1.1 on 2023-10-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
    ]
